# Generated by Django 5.2.8 on 2025-11-16 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(max_length=50)),
                ('id_proof_number', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resident_photos/')),
                ('status', models.CharField(choices=[('added', 'Added'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='added', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='resident_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.resident')),
            ],
        ),
    ]
